### ISSUE TITLE
Issue in no data zone in line.py line 196

### ISSUE THREAD

**Issue by bullocke** [ceholden/yatsm#48]
https://github.com/ceholden/yatsm/blob/master/yatsm/cli/line.py#L196

File "/usr3/graduate/valpasq/Documents/yatsm/yatsm/cli/line.py", line 196, in line
    output.extend(yatsm.record)
TypeError: 'NoneType' object is not iterable

Fix (tested):
Add if statement to check if record exists:

if yatsm.record is not None:
     output.extend(yatsm.record)

**Comment by bullocke** [comment]
https://github.com/ceholden/yatsm/blob/master/yatsm/cli/line.py#L196

**Comment by ceholden** [comment]
Doesn't this bit of code fix the issue? It does effectively the same thing but it is placed before the phenology calculation and refitting?

https://github.com/ceholden/yatsm/blob/master/yatsm/cli/line.py#L176
``` python
if yatsm.record is None:
    continue
...
output.extend(yatsm.record)
```

It seems like something else is going on since it should skip to the next column if the `yatsm.record` is `None`.

**Comment by ceholden** [comment]
Oops -- so this is basically a copy of #47. The fix I implemented didn't actually work:

When I check, `if yatsm.record is None`, `yatsm.record` isn't actually None -- it's just an empty `np.array`.  The refit or postprocess functions actually return `None` if the `yatsm.record` is empty so this is why your suggestion would work. I'm going to fix it even earlier on by actually correctly checking for an empty result.

**Comment by bullocke** [comment]
You would think...Val updated the script with line 176 fixed and was still getting the error. I had previously added that line and was not receiving the error for a full scene. I can test this more and report back.

**Comment by bullocke** [comment]
Makes sense, please notify when ready for checking and we will test.

**Comment by ceholden** [comment]
I tried it on Val's dataset and it worked. Can you give it a go? If it's working I'll re-tag this commit as v0.5.3 and re-release it.

**Comment by valpasq** [comment]
I pulled the latest fix, currently running on the /Massachusetts/p012r031/ dataset without issue, i.e. no error messages, YATSM results are being written. I think this issue can be closed.

**Comment by ceholden** [comment]
Sorry about that! Anyway as I mentioned I'm going to re-release `v0.5.3` by moving it one step further to this commit.
